/* grammar.c — the canonical tool-call body grammar, for AOT builds.
 *
 * Backs the AOT lowering of `llm.tool_grammar()`. This is a generation-time
 * constraint (a GBNF a caller pairs with a model's delimiters to force the
 * model to emit parseable tool calls), NOT tool-call parsing: parsing left the
 * runtime entirely and now ships with each model's profile as a Jade package.
 *
 * Target-independent (no socket, no pthread): links into both runtime backends.
 */

#include "runtime.h"

/* The canonical tool-call body grammar, generated by build.rs straight from
 * jadelang/grammars/tool_call.gbnf so it is byte-identical to the VM's
 * compiled-in copy (gbnf::TOOL_CALL_GBNF). */
#include "tool_call_gbnf.h"

/* llm.tool_grammar() — the grammar as a TRUSTED heap string. */
char* jrt_tool_grammar(void) {
    return jrt_str_dup(JRT_TOOL_CALL_GBNF, JRT_TRUSTED);
}
