/* tool_call.c — per-model tool-call vocabulary + parsing.
 *
 * A faithful C port of jadelang's src/llm/model_profile.rs (the VM is the
 * source of truth). Tool-call delimiters, the tool-name JSON field, and any
 * special-token spans are properties of the *model*, not of Jade or the wire
 * protocol, so they live here as plain data and everything downstream asks the
 * profile rather than hardcoding "<tool_call>".
 *
 * Backs the AOT lowering of llm.tool_grammar / llm.find_tool_call /
 * llm.find_tool_calls / llm.profile. Target-independent (no socket, no
 * pthread): same file links into both runtime backends. */

#include "runtime.h"

#include <ctype.h>
#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* The canonical tool-call body grammar, generated by build.rs straight from
 * jadelang/grammars/tool_call.gbnf so it is byte-identical to the VM's
 * compiled-in copy (gbnf::TOOL_CALL_GBNF). */
#include "tool_call_gbnf.h"

/* ── Model profile data (mirrors model_profile.rs::ModelProfile) ──────── */

typedef struct { const char* tag; const char* open; const char* close; } SpanDef;

typedef struct {
    const char*        model;          /* reported model name this profile targets */
    const char* const* match_patterns; /* `*`-globs; first match wins              */
    size_t             n_patterns;
    const char*        open;           /* tool_call.open delimiter                 */
    const char*        close;          /* tool_call.close delimiter                */
    const char*        name_field;     /* JSON field naming the tool               */
    const SpanDef*     spans;          /* extra special-token spans                */
    size_t             n_spans;
} ModelProfile;

/* Qwen3-Coder-30B — native Qwen/Hermes tool calls, no reasoning channel. */
static const char* const QWEN3_CODER_30B_PATTERNS[] = { "Qwen3-Coder*", "qwen3-coder*" };
static const ModelProfile QWEN3_CODER_30B = {
    .model          = "Qwen3-Coder-30B",
    .match_patterns = QWEN3_CODER_30B_PATTERNS,
    .n_patterns     = 2,
    .open           = "<tool_call>",
    .close          = "</tool_call>",
    .name_field     = "name",
    .spans          = NULL,
    .n_spans        = 0,
};

/* Every profile this build knows about. First match in select wins. */
static const ModelProfile* const PROFILES[] = { &QWEN3_CODER_30B };

/* `*`-glob match (no other metacharacters); ASCII byte comparison. Mirrors
 * model_profile.rs::glob_match so profile selection agrees on both sides. */
static int glob_match(const char* pattern, const char* text) {
    const unsigned char* p = (const unsigned char*)pattern;
    const unsigned char* t = (const unsigned char*)text;
    size_t plen = strlen(pattern), tlen = strlen(text);
    size_t pi = 0, ti = 0;
    int have_star = 0;
    size_t star = 0, mark = 0;
    while (ti < tlen) {
        if (pi < plen && p[pi] == t[ti]) {
            pi++; ti++;
        } else if (pi < plen && p[pi] == '*') {
            have_star = 1; star = pi; mark = ti; pi++;
        } else if (have_star) {
            pi = star + 1; mark++; ti = mark;
        } else {
            return 0;
        }
    }
    while (pi < plen && p[pi] == '*') pi++;
    return pi == plen;
}

/* The profile for `model_name` (exact name or any glob), or NULL if unknown. */
static const ModelProfile* select_profile(const char* model_name) {
    for (size_t i = 0; i < sizeof(PROFILES) / sizeof(PROFILES[0]); i++) {
        const ModelProfile* p = PROFILES[i];
        if (strcmp(p->model, model_name) == 0) return p;
        for (size_t j = 0; j < p->n_patterns; j++) {
            if (glob_match(p->match_patterns[j], model_name)) return p;
        }
    }
    return NULL;
}

/* The active profile, resolved against the runtime's model ($JADE_MODEL). */
static const ModelProfile* current_profile(void) {
    char* model = jrt_get_model();           /* TRUSTED heap copy, "" if unset */
    const ModelProfile* p = select_profile(model ? model : "");
    jrt_str_free(model);
    return p;
}

/* Build a {name, args} dict from a raw delimiter body (mirrors
 * ModelProfile::match_from_body): args = trimmed body (taint propagated from
 * the source text); name = name_field lifted from the JSON body, or "" when the
 * body isn't a JSON object or the field is absent. Returns a boxed dict. */
static jade_value_t make_tool_call(const ModelProfile* p,
                                   const char* body, size_t blen,
                                   uint8_t trust) {
    /* trim() */
    while (blen > 0 && isspace((unsigned char)body[0]))      { body++; blen--; }
    while (blen > 0 && isspace((unsigned char)body[blen-1])) { blen--; }

    char* args = jrt_str_new(blen, trust);
    if (blen > 0) memcpy(args, body, blen);

    /* Lift the tool name: parse the body as a JSON object and read name_field
     * if present as a string (jrt_json_parse is lenient — a non-object body
     * yields an empty dict, so a missing/invalid name reads back as nil). */
    char* name = NULL;
    void* d = jrt_json_parse(args);
    if (d) {
        int64_t nv = jade_dict_get(d, p->name_field);
        if (jrt_is_str(nv)) {
            name = jrt_str_dup((const char*)jrt_unbox_ptr(nv), trust);
        }
    }
    if (!name) name = jrt_str_dup("", trust);

    void* dict = jade_dict_create();
    jade_dict_set(dict, "name", jrt_box_str(name));
    jade_dict_set(dict, "args", jrt_box_str(args));
    return jrt_box_ptr(dict);
}

/* True if the JSON object span [body, body+blen) is a bare tool call — i.e. it
 * parses and carries the profile's name_field as a string. That field is the
 * only signal separating a tool call from arbitrary JSON the model emits as
 * prose. Mirrors the `name_field`-presence filter in model_profile.rs::
 * bare_tool_calls. */
static int bare_obj_is_tool_call(const ModelProfile* p,
                                 const char* body, size_t blen) {
    while (blen > 0 && isspace((unsigned char)body[0]))      { body++; blen--; }
    while (blen > 0 && isspace((unsigned char)body[blen-1])) { blen--; }
    if (blen == 0) return 0;
    char* tmp = jrt_str_new(blen, JRT_TRUSTED);
    memcpy(tmp, body, blen);
    void* d = jrt_json_parse(tmp);     /* copies what it keeps; tmp is ours to free */
    int ok = 0;
    if (d) ok = jrt_is_str(jade_dict_get(d, p->name_field));
    jrt_str_free(tmp);
    return ok;
}

/* Find the first balanced top-level JSON object in `text` (string-aware brace
 * matching: braces and `\"` escapes inside a string literal don't open or close
 * an object). On success returns 1, sets the object span (start + len) and
 * `*consumed` to the offset just past its closing '}'. Returns 0 if no
 * complete object is present. Mirrors model_profile.rs::first_object. */
static int first_object(const char* text, const char** obj_start,
                        size_t* obj_len, size_t* consumed) {
    size_t depth = 0, start = 0;
    int in_str = 0, escaped = 0;
    for (size_t i = 0; text[i]; i++) {
        char c = text[i];
        if (in_str) {
            if (escaped)        escaped = 0;
            else if (c == '\\') escaped = 1;
            else if (c == '"')  in_str = 0;
            continue;
        }
        if (c == '"') {
            in_str = 1;
        } else if (c == '{') {
            if (depth == 0) start = i;
            depth++;
        } else if (c == '}' && depth > 0) {
            depth--;
            if (depth == 0) {
                *obj_start = text + start;
                *obj_len   = i - start + 1;
                *consumed  = i + 1;
                return 1;
            }
        }
    }
    return 0;
}

/* Recover tool calls emitted as bare JSON (no open/close delimiters wrapping
 * them) — the path taken when the daemon strips the anchors because
 * keep_anchors was off. Walks every top-level JSON object (via first_object)
 * and, for each that qualifies as a tool call, pushes it onto `arr`. With
 * `first_only`, stops at and returns the first match (`arr` may be NULL);
 * otherwise returns JRT_NIL after pushing them all. A JSON array of calls
 * (`[{…},{…}]`) works too — the brackets don't affect brace depth. Mirrors
 * model_profile.rs::{scan_top_level_objects,bare_tool_calls}. */
static jade_value_t scan_bare_tool_calls(void* arr, const ModelProfile* p,
                                         const char* text, uint8_t trust,
                                         int first_only) {
    const char* rest = text;
    const char* obj;
    size_t olen, consumed;
    while (first_object(rest, &obj, &olen, &consumed)) {
        if (bare_obj_is_tool_call(p, obj, olen)) {
            jade_value_t tc = make_tool_call(p, obj, olen, trust);
            if (first_only) return tc;
            jrt_array_push(arr, tc);
        }
        rest += consumed;
    }
    return JRT_NIL;
}

/* ── Public entry points (declared in runtime.h) ──────────────────────── */

/* The canonical tool-call body grammar, as a TRUSTED heap string. */
char* jrt_tool_grammar(void) {
    return jrt_str_dup(JRT_TOOL_CALL_GBNF, JRT_TRUSTED);
}

/* First tool call in `text`, as a {name, args} dict, or nil when no profile is
 * known for the active model or no call is present. Mirrors
 * ModelProfile::find_tool_call: a delimited open without a close uses the
 * remainder; when no opening delimiter appears at all (anchors stripped because
 * keep_anchors was off), the first bare-JSON tool call is recovered instead. */
jade_value_t jrt_llm_find_tool_call(const char* text) {
    if (!text) return JRT_NIL;
    const ModelProfile* p = current_profile();
    if (!p) return JRT_NIL;

    const char* open_at = strstr(text, p->open);
    if (open_at) {
        const char* after = open_at + strlen(p->open);
        const char* close = strstr(after, p->close);
        size_t blen = close ? (size_t)(close - after) : strlen(after);
        return make_tool_call(p, after, blen, jrt_trust_of(text));
    }
    /* No delimiter in the stream → recover the first bare-JSON call. */
    return scan_bare_tool_calls(NULL, p, text, jrt_trust_of(text), /*first_only=*/1);
}

/* Every tool call in `text`, in order, as an array of {name, args} dicts.
 * Empty array when no profile is known or none are present. Mirrors
 * ModelProfile::find_all_tool_calls: at each `open` delimiter, take the BALANCED
 * JSON object that follows (via first_object) rather than slicing to the next
 * `close` — so a missing </tool_call> between two opens can't make the first
 * call swallow the second. */
jade_value_t jrt_llm_find_tool_calls(const char* text) {
    void* arr = jrt_array_new();
    const ModelProfile* p = current_profile();
    if (p && text) {
        uint8_t trust = jrt_trust_of(text);
        const char* rest = text;
        int found = 0;
        const char* open_at;
        while ((open_at = strstr(rest, p->open)) != NULL) {
            const char* after = open_at + strlen(p->open);
            const char* obj;
            size_t olen, consumed;
            if (first_object(after, &obj, &olen, &consumed)) {
                jrt_array_push(arr, make_tool_call(p, obj, olen, trust));
                found = 1;
                rest = after + consumed;
            } else {
                /* No JSON object after this open (malformed/truncated tail):
                 * fall back to the remainder, matching the VM's defensive finish. */
                jrt_array_push(arr, make_tool_call(p, after, strlen(after), trust));
                found = 1;
                break;
            }
        }
        /* No delimiters anywhere → recover bare-JSON calls (anchors stripped
         * because keep_anchors was off) so multi-call turns aren't dropped.
         * Only when the delimited scan found nothing, so delimited output keeps
         * its exact previous behavior. */
        if (!found) scan_bare_tool_calls(arr, p, text, trust, /*first_only=*/0);
    }
    return jrt_box_ptr(arr);
}

/* The active model's profile as a dict
 * { model, tool_call:{open,close,name_field}, spans:[{tag,open,close}] },
 * or nil when unknown. Mirrors vm.rs::model_profile_to_vm. Profile data is
 * static/program-controlled, so its strings are TRUSTED. */
jade_value_t jrt_llm_profile(void) {
    const ModelProfile* p = current_profile();
    if (!p) return JRT_NIL;

    void* tool_call = jade_dict_create();
    jade_dict_set(tool_call, "open",       jrt_box_str(jrt_str_dup(p->open, JRT_TRUSTED)));
    jade_dict_set(tool_call, "close",      jrt_box_str(jrt_str_dup(p->close, JRT_TRUSTED)));
    jade_dict_set(tool_call, "name_field", jrt_box_str(jrt_str_dup(p->name_field, JRT_TRUSTED)));

    void* spans = jrt_array_new();
    for (size_t i = 0; i < p->n_spans; i++) {
        void* s = jade_dict_create();
        jade_dict_set(s, "tag",   jrt_box_str(jrt_str_dup(p->spans[i].tag, JRT_TRUSTED)));
        jade_dict_set(s, "open",  jrt_box_str(jrt_str_dup(p->spans[i].open, JRT_TRUSTED)));
        jade_dict_set(s, "close", jrt_box_str(jrt_str_dup(p->spans[i].close, JRT_TRUSTED)));
        jrt_array_push(spans, jrt_box_ptr(s));
    }

    void* dict = jade_dict_create();
    jade_dict_set(dict, "model",     jrt_box_str(jrt_str_dup(p->model, JRT_TRUSTED)));
    jade_dict_set(dict, "tool_call", jrt_box_ptr(tool_call));
    jade_dict_set(dict, "spans",     jrt_box_ptr(spans));
    return jrt_box_ptr(dict);
}
