//! Generate a Jade-ABI binding shim for a plain C library.
//!
//! The loader requires a `jade_pkg_init` symbol (`src/native/mod.rs`), which an
//! ordinary C library like `libz` does not have. Rather than teach the runtime
//! to dispatch arbitrary C signatures — which would mean a `libffi` dependency
//! and *two* implementations of the marshalling, one for the VM and one for the
//! AOT runtime — this emits a small C file that wraps each declared symbol and
//! exports a real `jade_pkg_init`. It compiles with `cc`, which `jade build`
//! already shells out to, and the result is an ordinary Jade-ABI package that
//! both backends already know how to load.
//!
//! The type vocabulary is exactly the FFI's: `int`, `float`, `bool`, `str`, and
//! `nil` (return only). That is a real limit — a C function taking a struct
//! pointer cannot be bound — but it is the same limit the ABI imposes
//! everywhere, and rejecting it here names the symbol instead of silently
//! marshalling an argument to nil.

use std::collections::HashMap;

use crate::project::CSymbol;

/// How one Jade FFI type appears in generated C.
struct CType {
    /// The C spelling used in the extern declaration.
    decl: &'static str,
    /// `JADE_FFI_*` tag constant.
    tag: &'static str,
    /// Field of `JadeValData` holding it.
    field: &'static str,
}

fn map_type(t: &str) -> Option<CType> {
    Some(match t {
        "int" => CType { decl: "int64_t", tag: "JADE_FFI_INT", field: "as_int" },
        "float" => CType { decl: "double", tag: "JADE_FFI_FLOAT", field: "as_float" },
        "bool" => CType { decl: "uint8_t", tag: "JADE_FFI_BOOL", field: "as_bool" },
        "str" => CType { decl: "const char*", tag: "JADE_FFI_STR", field: "as_str" },
        _ => return None,
    })
}

const SUPPORTED_TYPES: &str = "int, float, bool, str (and nil for a return type)";

/// The ABI declarations every shim needs. Must stay byte-compatible with
/// `JadeVal`/`JadeBinding`/`JadeNativePkg` in `src/native/mod.rs` — note the
/// seven padding bytes, which are load-bearing for the struct layout.
const PREAMBLE: &str = r#"/* Generated by `jade pkg install` — do not edit.
 * Binding shim: wraps a plain C library in the Jade native package ABI. */
#include <stdint.h>
#include <stddef.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>

#define JADE_FFI_NIL   0
#define JADE_FFI_INT   1
#define JADE_FFI_FLOAT 2
#define JADE_FFI_BOOL  3
#define JADE_FFI_STR   4
#define JADE_FFI_ERROR 5

typedef union {
    int64_t     as_int;
    double      as_float;
    uint8_t     as_bool;
    const char* as_str;
    uint64_t    as_nil;
} JadeValData;

typedef struct { uint8_t tag; uint8_t _pad[7]; JadeValData data; } JadeVal;
typedef int (*JadeNativeFnPtr)(size_t argc, const JadeVal* argv, JadeVal* out);
typedef struct { const char* name; JadeNativeFnPtr func; } JadeBinding;
typedef struct { const char* name; const JadeBinding* bindings; size_t binding_count; } JadeNativePkg;

/* Describe the failure the library just reported.
 *
 * The buffer is _Thread_local because Jade tasks are real OS threads and two of
 * them can be inside different failing calls at once. Returning it borrowed is
 * safe under the ABI's output-string rule: both engines copy the message before
 * the native call returns.
 *
 * strerror_r is used where POSIX guarantees it, because plain strerror shares
 * one buffer across threads. The two signatures disagree about what they
 * return, hence the split — GNU hands back a pointer that may not be `buf` at
 * all, and ignoring that is how a message ends up empty. */
static const char* jade_shim_errmsg(void) {
    static _Thread_local char buf[256];
    int e = errno;
    if (e == 0) {
        /* The convention said failure but errno was never set. Say exactly
         * that rather than inventing "Success", which is what strerror(0)
         * would return and reads as a bug in Jade. */
        snprintf(buf, sizeof buf, "the call reported failure but set no errno");
        return buf;
    }
#if defined(__GLIBC__) && defined(_GNU_SOURCE)
    char tmp[192];
    const char* msg = strerror_r(e, tmp, sizeof tmp);
    snprintf(buf, sizeof buf, "%s (errno %d)", msg ? msg : "unknown error", e);
#elif (defined(_POSIX_C_SOURCE) && _POSIX_C_SOURCE >= 200112L) || defined(__APPLE__)
    char tmp[192];
    if (strerror_r(e, tmp, sizeof tmp) != 0) snprintf(tmp, sizeof tmp, "unknown error");
    snprintf(buf, sizeof buf, "%s (errno %d)", tmp, e);
#else
    snprintf(buf, sizeof buf, "%s (errno %d)", strerror(e), e);
#endif
    return buf;
}
"#;

/// Emit the shim's C source for `symbols`.
///
/// Symbols are emitted in sorted order so a reinstall produces an identical
/// file rather than churning with `HashMap` iteration order.
pub fn generate(name: &str, symbols: &HashMap<String, CSymbol>) -> Result<String, String> {
    if symbols.is_empty() {
        return Err(format!("dependency '{name}': no symbols declared for the C binding shim"));
    }

    let mut names: Vec<&String> = symbols.keys().collect();
    names.sort();

    let mut out = String::from(PREAMBLE);
    out.push('\n');

    for sym in &names {
        out.push_str(&declare(name, sym, &symbols[*sym])?);
    }
    for sym in &names {
        out.push_str(&wrapper(name, sym, &symbols[*sym])?);
    }

    out.push_str("static const JadeBinding BINDINGS[] = {\n");
    for sym in &names {
        out.push_str(&format!("    {{ \"{sym}\", jade_shim_{sym} }},\n"));
    }
    out.push_str("};\n\n");

    out.push_str(&format!(
        "int jade_pkg_init(JadeNativePkg* out) {{\n\
         \x20   out->name = \"{name}\";\n\
         \x20   out->bindings = BINDINGS;\n\
         \x20   out->binding_count = sizeof(BINDINGS) / sizeof(BINDINGS[0]);\n\
         \x20   return 0;\n\
         }}\n"
    ));

    Ok(out)
}

/// `extern` prototype for the target library's symbol.
fn declare(pkg: &str, sym: &str, spec: &CSymbol) -> Result<String, String> {
    let ret = match spec.ret.as_str() {
        "nil" => {
            // A void call returns no sentinel, so there is nothing for a failure
            // convention to test. Saying so beats generating a shim that quietly
            // ignores the declaration.
            if spec.fails_when.is_some_and(|f| f.test().is_some()) {
                return Err(format!(
                    "dependency '{pkg}': symbol '{sym}' declares `fails_when` but returns nil, \
                     so there is no return value to test. Give it a return type, or drop \
                     `fails_when`."
                ));
            }
            "void".to_string()
        }
        other => bad_type(pkg, sym, other)?.decl.to_string(),
    };
    let args = if spec.args.is_empty() {
        "void".to_string()
    } else {
        spec.args
            .iter()
            .map(|a| bad_type(pkg, sym, a).map(|t| t.decl.to_string()))
            .collect::<Result<Vec<_>, _>>()?
            .join(", ")
    };
    Ok(format!("extern {ret} {sym}({args});\n"))
}

/// The `JadeNativeFnPtr`-shaped wrapper that marshals in and out.
fn wrapper(pkg: &str, sym: &str, spec: &CSymbol) -> Result<String, String> {
    let mut body = String::new();
    body.push_str(&format!(
        "\nstatic int jade_shim_{sym}(size_t argc, const JadeVal* argv, JadeVal* out) {{\n"
    ));
    body.push_str(&format!("    if (argc != {}) return 1;\n", spec.args.len()));

    // Arity and tags are checked before the call: a wrong-typed argument would
    // otherwise be reinterpreted through the union and hand the C function
    // garbage.
    let mut call_args = Vec::new();
    for (i, arg) in spec.args.iter().enumerate() {
        let t = bad_type(pkg, sym, arg)?;
        body.push_str(&format!("    if (argv[{i}].tag != {}) return 1;\n", t.tag));
        call_args.push(format!("argv[{i}].data.{}", t.field));
    }

    let call = format!("{sym}({})", call_args.join(", "));
    // Cleared right before the call so a stale value from an earlier, unrelated
    // failure cannot be reported as this one's reason. A successful call is
    // allowed to leave errno set, which is why only the failure branch reads it.
    let fail_test = spec.fails_when.and_then(|f| f.test());
    if fail_test.is_some() {
        body.push_str("    errno = 0;\n");
    }

    match spec.ret.as_str() {
        "nil" => {
            body.push_str(&format!("    {call};\n"));
            // A void function has no sentinel to test, so a declared convention
            // has nothing to read. `declare` rejects that pairing outright.
            body.push_str("    out->tag = JADE_FFI_NIL;\n");
            body.push_str("    out->data.as_nil = 0;\n");
        }
        other => {
            let t = bad_type(pkg, sym, other)?;
            body.push_str(&format!("    {} r = {call};\n", t.decl));
            if let Some(test) = fail_test {
                // Status 1 with an ERROR tag is what both engines turn into a
                // catchable Jade raise; the message is borrowed, and both copy
                // it before returning.
                body.push_str(&format!("    if ({test}) {{\n"));
                body.push_str("        out->tag = JADE_FFI_ERROR;\n");
                body.push_str("        out->data.as_str = jade_shim_errmsg();\n");
                body.push_str("        return 1;\n");
                body.push_str("    }\n");
            }
            body.push_str(&format!("    out->tag = {};\n", t.tag));
            body.push_str(&format!("    out->data.{} = r;\n", t.field));
        }
    }

    body.push_str("    return 0;\n}\n");
    Ok(body)
}

fn bad_type(pkg: &str, sym: &str, t: &str) -> Result<CType, String> {
    map_type(t).ok_or_else(|| {
        format!(
            "dependency '{pkg}': symbol '{sym}' uses type '{t}', which the Jade FFI cannot \
             represent. Supported types are {SUPPORTED_TYPES}."
        )
    })
}

#[cfg(test)]
mod tests;
